### PR TITLE
Fix join and plusWith

### PR DESCRIPTION
**Pull request by NekodRider**
#46

### CODE REVIEW

**Comment by NekodRider** [comment]
https://github.com/GraiaProject/Application/blob/99be4c49b75246bb7cdd32e81e213c9f59bf3a55/src/graia/scheduler/task.py#L88-L102

报错 `TypeError: Executor() got an unexpected keyword argument 'target'`

这里第二个 yield 里的 self.broadcast.Executor 参数好像错了 应该先构造 ExecutorProtocol 才对

**Comment by GreyElaina** [comment]
> https://github.com/GraiaProject/Application/blob/99be4c49b75246bb7cdd32e81e213c9f59bf3a55/src/graia/scheduler/task.py#L88-L102
> 
> 报错 `TypeError: Executor() got an unexpected keyword argument 'target'`
> 
> 这里第二个 yield 里的 self.broadcast.Executor 参数好像错了 应该先构造 ExecutorProtocol 才对

请更新 `graia-broadcast`.

**Review by GreyElaina — CHANGES_REQUESTED** [review]
去掉关于 `graia.scheduler.task` 的更改, 你该更新下 `graia-broadcast` 的版本了.

**Comment by NekodRider** [comment]
更新后的确可以了，已撤销修改，感觉可以更新下库依赖版本要求，用 pipdeptree 看现在的 `graia-broadcast` 版本要求是 `*`

<pre>
graia-application-mirai==0.10.6
  - aiohttp [required: >=3.6.2,<4.0.0, installed: 3.6.2]
    - async-timeout [required: >=3.0,<4.0, installed: 3.0.1]
    - attrs [required: >=17.3.0, installed: 20.2.0]
    - chardet [required: >=2.0,<4.0, installed: 3.0.4]
    - multidict [required: >=4.5,<5.0, installed: 4.7.6]
    - yarl [required: >=1.0,<2.0, installed: 1.5.1]
      - idna [required: >=2.0, installed: 2.10]
      - multidict [required: >=4.0, installed: 4.7.6]
  - croniter [required: >=0.3.34,<0.4.0, installed: 0.3.34]
    - natsort [required: Any, installed: 7.0.1]
    - python-dateutil [required: Any, installed: 2.8.1]
      - six [required: >=1.5, installed: 1.15.0]
  - <b>graia-broadcast [required: Any, installed: 0.3.1]</b>
    - iterwrapper [required: >=0.1.2,<0.2.0, installed: 0.1.4]
    - pydantic [required: >=1.5.1,<2.0.0, installed: 1.6.1]
  - pydantic [required: >=1.6.1,<2.0.0, installed: 1.6.1]
  - regex [required: >=2020.7.14,<2021.0.0, installed: 2020.7.14]
  - yarl [required: >=1.4.2,<2.0.0, installed: 1.5.1]
    - idna [required: >=2.0, installed: 2.10]
    - multidict [required: >=4.0, installed: 4.7.6]
</pre>

**Review by GreyElaina — APPROVED** [review]

**Pull request merged**
